name: Build and Deploy Expo App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Expo app
        run: npx expo export --output-dir web-build

      - name: List files in web-build
        run: ls -R web-build

      - name: Display contents of build directory (before copy)
        run: |
          echo "Listing contents of build directory before copying:"
          ls -al /home/runner/work/MobileTemplateFork3/MobileTemplateFork3/web-build
      - name: Display contents of build directory M3 (before copy)
        run: |
          echo "Listing contents of build directory before copying M3:"
          ls -al /home/runner/work/MobileTemplateFork3

      - name: Display contents of build directory M3 M3 (before copy)
        run: |
          echo "Listing contents of build directory before copying M3:"
          ls -al /home/runner/work/MobileTemplateFork3

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./web-build
      #     publish_branch: gh-pages
      #     allow_empty_commit: false
      #     keep_files: false
      #     force_orphan: false
      #     enable_jekyll: false
      #     disable_nojekyll: false
      #     exclude_assets: .github
